### ISSUE TITLE
Invalid API Key error

### ISSUE THREAD

**Issue by abizermamnoon** [mikeizbicki/cmc-csci181-languages#3]
I am getting the following error:

```
(venv) amamnoon@abizer:~/cs_181/proj/docsum$ python3 docsum.py docs/'Abizer Mamnoon Resume.pdf'
Traceback (most recent call last):
  File "/home/amamnoon/cs_181/proj/docsum/docsum.py", line 25, in <module>
    chat_completion = client.chat.completions.create(
  File "/home/amamnoon/cs_181/proj/docsum/venv/lib/python3.10/site-packages/groq/resources/chat/completions.py", line 289, in create
    return self._post(
  File "/home/amamnoon/cs_181/proj/docsum/venv/lib/python3.10/site-packages/groq/_base_client.py", line 1225, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/amamnoon/cs_181/proj/docsum/venv/lib/python3.10/site-packages/groq/_base_client.py", line 920, in request
    return self._request(
  File "/home/amamnoon/cs_181/proj/docsum/venv/lib/python3.10/site-packages/groq/_base_client.py", line 1018, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.AuthenticationError: Error code: 401 - {'error': {'message': 'Invalid API Key', 'type': 'invalid_request_error', 'code': 'invalid_api_key'}}
```

I do not get above error when i paste API key in my code. This is my code right now:
```
import os
from groq import Groq
#from dotenv import load_dotenv
import argparse
import fulltext
#filename = 'docs/declaration'
#with open(args.filename) as f:
#    text = f.read()
# Load environment variables from .env file
# Set up argument parser
parser = argparse.ArgumentParser()
parser.add_argument('filename')
args = parser.parse_args()

# Use fulltext to extract text from the file
text = fulltext.get(args.filename)
print(os.environ.get("GROQ_API_KEY"))
# Initialize Groq client with API key
client = Groq(
    # This is the default and can be omitted
    api_key=os.environ.get("GROQ_API_KEY"),
)


chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "system",
            "content": "summarize input text below. limit summary to 1 paragraph and use a 1st grade reading level",
        },
        {
            "role": "user",
            "content":text,
        }
    ],
    model="llama3-8b-8192",
)
print(chat_completion.choices[0].message.content)
```

The print statement also gives the API key so I am sure that the API key is being referenced correctly from .env file

**Comment by mikeizbicki** [comment]
You are probably somehow including a space or some other weird characters in the key when you load it.  I'd have to see in person though to verify the problem.
